apiVersion: v1
kind: Secret
metadata:
  name: login-app-secret
  labels:
    app: login-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_USER: "loginuser"
  MYSQL_PASSWORD: "loginpassword"
  SESSION_SECRET: "k8s-production-super-secret-session-key"
